///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavoriteModelData {
/*
{
  "productId": 3,
  "image": "10764967084082.jpg",
  "price": 7800,
  "title": "Yazıcı"
} 
*/

  int? productId;
  String? image;
  int? price;
  String? title;
  bool? isFavorite;

  FavoriteModelData({
    this.productId,
    this.image,
    this.price,
    this.title,
    this.isFavorite,
  });
  FavoriteModelData.fromJson(Map<String, dynamic> json) {
    productId = json['productId']?.toInt();
    image = json['image']?.toString();
    price = json['price']?.toInt();
    title = json['title']?.toString();
    isFavorite = json['isFavorite'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['productId'] = productId;
    data['image'] = image;
    data['price'] = price;
    data['title'] = title;
    data['isFavorite'] = isFavorite;
    return data;
  }
}

class FavoriteModel {
/*
{
  "message": "Favorilerdeki ürünler başarıyla getirildi",
  "status": true,
  "data": [
    {
      "productId": 3,
      "image": "10764967084082.jpg",
      "price": 7800,
      "title": "Yazıcı"
    }
  ]
} 
*/

  String? message;
  bool? status;
  List<FavoriteModelData?>? data;

  FavoriteModel({
    this.message,
    this.status,
    this.data,
  });
  FavoriteModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FavoriteModelData>[];
      v.forEach((v) {
        arr0.add(FavoriteModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
