///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchModelDataSearchList {
/*
{
  "id": 2,
  "price": 17800,
  "title": "Samsung",
  "image": "10698988879922.jpg"
} 
*/

  int? id;
  int? price;
  String? title;
  String? image;
  bool? isFavorite;

  SearchModelDataSearchList({
    this.id,
    this.price,
    this.title,
    this.image,
    this.isFavorite,
  });
  SearchModelDataSearchList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    price = json['price']?.toInt();
    title = json['title']?.toString();
    image = json['image']?.toString();
    isFavorite = json['isFavorite'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    data['title'] = title;
    data['image'] = image;
    data['isFavorite'] = isFavorite;
    return data;
  }
}

class SearchModelData {
/*
{
  "searchList": [
    {
      "id": 2,
      "price": 17800,
      "title": "Samsung",
      "image": "10698988879922.jpg"
    }
  ]
} 
*/

  List<SearchModelDataSearchList?>? searchList;

  SearchModelData({
    this.searchList,
  });
  SearchModelData.fromJson(Map<String, dynamic> json) {
    if (json['searchList'] != null) {
      final v = json['searchList'];
      final arr0 = <SearchModelDataSearchList>[];
      v.forEach((v) {
        arr0.add(SearchModelDataSearchList.fromJson(v));
      });
      searchList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (searchList != null) {
      final v = searchList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['searchList'] = arr0;
    }
    return data;
  }
}

class SearchModel {
/*
{
  "message": "Ürünler başarıyla getirildi",
  "status": true,
  "data": {
    "searchList": [
      {
        "id": 2,
        "price": 17800,
        "title": "Samsung",
        "image": "10698988879922.jpg"
      }
    ]
  }
} 
*/

  String? message;
  bool? status;
  SearchModelData? data;

  SearchModel({
    this.message,
    this.status,
    this.data,
  });
  SearchModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
    data =
        (json['data'] != null) ? SearchModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
