///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserUpdateModel {
/*
{
  "message": "Kullanıcı bilgileri başarıyla güncellendi",
  "status": true
} 
*/

  String? message;
  bool? status;

  UserUpdateModel({
    this.message,
    this.status,
  });
  UserUpdateModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
