///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModelData {
/*
{
  "name": "Ahmet",
  "phone": 5551911546,
  "email": "ahmet@ahmet.com",
  "avatar": "default.jpg"
} 
*/

  String? name;
  int? phone;
  String? email;
  String? avatar;

  UserModelData({
    this.name,
    this.phone,
    this.email,
    this.avatar,
  });
  UserModelData.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    phone = json['phone']?.toInt();
    email = json['email']?.toString();
    avatar = json['avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['phone'] = phone;
    data['email'] = email;
    data['avatar'] = avatar;
    return data;
  }
}

class UserModel {
/*
{
  "message": "Kullanıcı bilgileri başarıyla getirildi",
  "status": true,
  "data": {
    "name": "Ahmet",
    "phone": 5551911546,
    "email": "ahmet@ahmet.com",
    "avatar": "default.jpg"
  }
} 
*/

  String? message;
  bool? status;
  UserModelData? data;

  UserModel({
    this.message,
    this.status,
    this.data,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
    data = (json['data'] != null) ? UserModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
